# .air.toml
[build]
  cmd = "go build -o ./tmp/main -buildvcs=false ./main.go"
  bin = "./tmp/main"
  log = "air.log"

[watch]
  delay = 1000 # delay in ms
  includes = [
    "pkg/**/*"
  ]
  excludes = [
    "assets",
    "tmp"
  ]

[log]
  level = "debug"