version: '3.8'

services:
  app:
    container_name: go-gin-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    command: air
    depends_on:
      - db
      - nyckeln
      - redis
    environment:
      - ENV=dev
      - DB_HOST=db
      - DB_USER=ticketuser
      - DB_PASSWORD=yourpassword
      - DB_NAME=ticketdb
      - DB_PORT=5432
      - DB_SSLMODE=disable  # or your preferred SSL mode
      - LOGIN_BASE_URL=http://nyckeln:7002
      - REDIS_URL=redis:6379
    volumes:
      - .:/app

  db:
    container_name: postgres-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: ticketuser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://ticketuser:yourpassword@db:5432/ticketdb?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
    
  nyckeln:
    container_name: nyckeln-service
    image: ghcr.io/datasektionen/nyckeln-under-dorrmattan
    platform: linux/amd64
    ports:
      - "7002:7002"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  redis_exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis://redis:6379"
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest  # Use an appropriate version
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount the configuration
      - prometheus_data:/prometheus  # Persist Prometheus data
    ports:
      - "9090:9090"
    depends_on:
      - app  # Ensure Prometheus starts after your application

  grafana:
    image: grafana/grafana:latest  # Use an appropriate version
    volumes:
      - grafana_data:/var/lib/grafana  # Persist Grafana data
    ports:
      - "3000:3000"
    depends_on:
      - prometheus  # Ensure Grafana starts after Prometheus

volumes:
  postgres-data:
  prometheus_data:  # Define the Prometheus data volume
  grafana_data:  # Define the Grafana data volume
