global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gin-application'
    static_configs:
      - targets: ['app:8080']
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']